-d C:\Users\Nadhir\Desktop\TP Transmission reception Verilog\UART IP\impl\gwsynthesis\UART IP.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cfg C:\Users\Nadhir\Desktop\TP Transmission reception Verilog\UART IP\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
